---
title: "STM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import relevant libraries and load the data

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(tidytext)
library(stm)
library(ggplot2)

file_path = "C:/Users/jawo19ad/Dropbox (CBS)/Master thesis data/Event Dataframes/Clean"
greece_path_001 = paste(file_path,"/df_greece_fi_test.csv", sep = "")
df_greece_raw <- read.csv(file = greece_path_001,
                          stringsAsFactors = FALSE)
df_greece_raw$day <- cumsum(!duplicated(df_greece_raw$date))
```



```{r}
# --------------------------------------------------------
# ------------------- Greece 001 -------------------------
# --------------------------------------------------------
df_greece_001 <- df_greece_raw %>% select(text_frame_identification_001, text_coherent, day)

processed_greece_001 = textProcessor(df_greece_001$text_frame_identification_001, metadata = df_greece_001,
                                 lowercase = FALSE,
                                 removestopwords = FALSE,
                                 removenumbers = FALSE,
                                 removepunctuation = FALSE,
                                 ucp = FALSE,
                                 stem = FALSE,
                                 customstopwords = FALSE)

out_greece_001 <- prepDocuments(processed_greece_001$documents,
                                processed_greece_001$vocab,
                                processed_greece_001$meta)

model_greece_6_001 <- stm(documents = out_greece_001$documents,
                          vocab = out_greece_001$vocab,
                          K = 6,
                          #prevalence =~ entity + s(day),
                          data = out_greece_001$meta,
                          init.type = "Spectral",
                          max.em.its = 15,
                          seed = 42)
```


```{r}
# --------------------------------------------------------
# ------------------- Greece 0025 ------------------------
# --------------------------------------------------------

df_greece_0025 <- df_greece_raw %>% select(text_frame_identification_0025, text_coherent, day)

processed_greece_0025 = textProcessor(df_greece_0025$text_frame_identification_0025, metadata = df_greece_0025,
                                 lowercase = FALSE,
                                 removestopwords = FALSE,
                                 removenumbers = FALSE,
                                 removepunctuation = FALSE,
                                 ucp = FALSE,
                                 stem = FALSE,
                                 customstopwords = FALSE)

out_greece_0025 <- prepDocuments(processed_greece_0025$documents,
                                processed_greece_0025$vocab,
                                processed_greece_0025$meta)

model_greece_6_0025 <- stm(documents = out_greece_0025$documents,
                          vocab = out_greece_0025$vocab,
                          K = 6,
                          #prevalence =~ entity + s(day),
                          data = out_greece_0025$meta,
                          init.type = "Spectral",
                          max.em.its = 15,
                          seed = 42)

```


```{r}
# --------------------------------------------------------
# ------------------- Greece 005 -------------------------
# --------------------------------------------------------

df_greece_005 <- df_greece_raw %>% select(text_frame_identification_005, text_coherent, day)

processed_greece_005 = textProcessor(df_greece_005$text_frame_identification_005, metadata = df_greece_005,
                                 lowercase = FALSE,
                                 removestopwords = FALSE,
                                 removenumbers = FALSE,
                                 removepunctuation = FALSE,
                                 ucp = FALSE,
                                 stem = FALSE,
                                 customstopwords = FALSE)

out_greece_005 <- prepDocuments(processed_greece_005$documents,
                                processed_greece_005$vocab,
                                processed_greece_005$meta)

model_greece_6_005 <- stm(documents = out_greece_005$documents,
                          vocab = out_greece_005$vocab,
                          K = 6,
                          #prevalence =~ entity + s(day),
                          data = out_greece_005$meta,
                          init.type = "Spectral",
                          max.em.its = 15,
                          seed = 42)
```


```{r}
# --------------------------------------------------------
# ------------------- Greece 01 -------------------------
# --------------------------------------------------------
df_greece_01 <- df_greece_raw %>% select(text_frame_identification_01, text_coherent, day)

processed_greece_01 = textProcessor(df_greece_01$text_frame_identification_01, metadata = df_greece_01,
                                 lowercase = FALSE,
                                 removestopwords = FALSE,
                                 removenumbers = FALSE,
                                 removepunctuation = FALSE,
                                 ucp = FALSE,
                                 stem = FALSE,
                                 customstopwords = FALSE)

out_greece_01 <- prepDocuments(processed_greece_01$documents,
                                processed_greece_01$vocab,
                                processed_greece_01$meta)

model_greece_6_01 <- stm(documents = out_greece_01$documents,
                          vocab = out_greece_01$vocab,
                          K = 6,
                          #prevalence =~ entity + s(day),
                          data = out_greece_01$meta,
                          init.type = "Spectral",
                          max.em.its = 15,
                          seed = 42)

```

```{r}
model_greece <- model_greece_6_005

# Plot the convergence
plot(model_greece$convergence$bound,
     type = "l",
     ylab = "Approximate Convergence",
     main = "Convergence")

# Label Topics
x = labelTopics(model = model_greece,
            n = 10)
x$frex

# Plot frequency of topics
plot(model_greece, type="summary", label="frex")

# Plot topic correlations
mod.out.corr <-topicCorr(model_greece)
plot(mod.out.corr)

?toLDAvis
toLDAvis(model_greece, docs = out_greece_005$documents)

```

